### PR TITLE
feat: Possibility for original schema string in objects Meta class.

### PR DESCRIPTION
**Pull request by bengels97**
(ModelGenerator-in-generator.py,-templates.py)
Added new template and "original_schema" key check in metadata_field_templates to allow adding of original schema string in class meta class field "original_schema"

We noticed it's possible for the generated avro schema, from the generated models, to deviate from the original schema. In order to guarantee exact matching, the original schema can be included in the models themselves.

Original issue: https://github.com/marcosschroh/dataclasses-avroschema/issues/544 

Curious to hear your thoughts on this. It's a nice workaround for our issue without breaking anything of the original functionality. I've tried to leverage the existing code base. But as you'll find, the possibility of including the original schema string is not obvious from the current code as is. 

P.S: Also went ahead to fix, what seemed to be a typo, matadata_field_templates -> metadata_field_templates

### CODE REVIEW

**Comment by marcosschroh** [comment]
Thanks for the PR.

Ideally, the generated model must match perfectly the original schema, unfortunately is not the case for `avro types` that have `inner names` (arrays, enums, fixed and maps).  This [issue](https://github.com/marcosschroh/dataclasses-avroschema/issues/534) is similar to your problem.

We can use your solution until we implement a new fix.

Regarding the PR I have suggestions:

1. Include the new template by default, so end users won't have to specify all the templates
2. Add a new option to `ModelGenerator` called `include_original_schema` with default to False. Then the end user can render the original schema:
   ```python
  model_generator = ModelGenerator(include_original_schema=True)`
  ```

**Comment by bengels97** [comment]
Where would you like me to add the new feature in the docs? Does it fit with one of the existing doc files or should I create a new one?

**Comment by bengels97** [comment]
I have implemented your feedback and included the new feature in the docs of model_generator.

**Comment by bengels97** [comment]
All pipelines are completing successfully now, with the exception of the deploy-preview though.

Seems there is an issue with the pipeline itself? 
image

**Pull request merged**
