### PR TITLE
fix: new style type annotations don't work for containers and maps

### PR DESCRIPTION
**Pull request by judahrand**
```python
class MyModel(AvroModel):
    my_dict: dict[str, Any]
    my_list: list[int]
    my_tuple: tuple[str]
```

Would previously fail

### CODE REVIEW

**Comment by judahrand** [comment]
That `codecov` failure just seems wrong...

**Comment by marcosschroh** [comment]
Looking good. Shall we add a test for python `3.10`? 

```python
@pytest.mark.skipif(sys.version_info < (3, 10), reason="requires python3.10 or higher")
def test_function():
    # Test containers and maps for 3.10 using dict, list and tuple as types
    ...
```

**Comment by judahrand** [comment]
> Looking good. Shall we add a test for python `3.10`?
> 
> ```python
> @pytest.mark.skipif(sys.version_info < (3, 10), reason="requires python3.10 or higher")
> def test_function():
>     # Test containers and maps for 3.10 using dict, list and tuple as types
>     ...
> ```

I'm not sure I understand what you mean?

I added `list`, `tuple` and `dict` to the tests and marked them as expected to fail (which I feel is generally better practice than skipping them but I don't feel that strongly).

Furthermore, this issue isn't a 3.10 issue it's a >=3.9 issue. Hence I mark `xfail` if below 3.9.

**Comment by marcosschroh** [comment]
Oh, sorry. I missed that you add the types  😔 .  

```python
SEQUENCE_TYPES = (typing.List, typing.Tuple, typing.Sequence, typing.MutableSequence, list, tuple)   # added list and tuple
MAPPING_TYPES = (typing.Dict, typing.Mapping, typing.MutableMapping, dict)  # added dict
```

**Pull request merged**
