### PR TITLE
Serdes speed-ups

### LINKED ISSUE #536: Improve performance of serdes methods
**Is your feature request related to a problem? Please describe.**

Serializing via the library is slower than using `fastavro` directly by orders of magnitude. This amounts to over 80% of the total time spent outside of the actual `fastavro` serdes.
There are a few simple reasons:

**- re-generating the schema(s) every time it _serializes and deserializes_ is inefficient**
https://github.com/marcosschroh/dataclasses-avroschema/blob/8150aaab43d8b9f12af64bd96da5f6af5517b882/dataclasses_avroschema/schema_generator.py#L122-L123
https://github.com/marcosschroh/dataclasses-avroschema/blob/8150aaab43d8b9f12af64bd96da5f6af5517b882/dataclasses_avroschema/schema_generator.py#L131-L144

**- re-computing the `dacite` config every time it _deserializes_ (which in turn re-generates the schema) is inefficient**

https://github.com/marcosschroh/dataclasses-avroschema/blob/8150aaab43d8b9f12af64bd96da5f6af5517b882/dataclasses_avroschema/schema_generator.py#L150
https://github.com/marcosschroh/dataclasses-avroschema/blob/8150aaab43d8b9f12af64bd96da5f6af5517b882/dataclasses_avroschema/schema_generator.py#L157-L158
https://github.com/marcosschroh/dataclasses-avroschema/blob/8150aaab43d8b9f12af64bd96da5f6af5517b882/dataclasses_avroschema/schema_generator.py#L173-L181

**- re-evaluating whether a `class` is a `pydantic` model repeatedly when _serializing_ is inefficient**

https://github.com/marcosschroh/dataclasses-avroschema/blob/8150aaab43d8b9f12af64bd96da5f6af5517b882/dataclasses_avroschema/schema_generator.py#L122-L126

https://github.com/marcosschroh/dataclasses-avroschema/blob/8150aaab43d8b9f12af64bd96da5f6af5517b882/dataclasses_avroschema/utils.py#L67-L77
https://github.com/marcosschroh/dataclasses-avroschema/blob/8150aaab43d8b9f12af64bd96da5f6af5517b882/dataclasses_avroschema/utils.py#L17-L20

**Describe the solution you'd like**
My suggestion would be:
- caching the class's own schema
- caching the class's own `dacite` config
- decorate `is_pydantic_model` with `lru_cache(maxsize=None)` (assuming no one is turning  their classes into pydantic models dynamically)

**Describe alternatives you've considered**
I think the simplest implementation would be caching the schema and the config in some global mappings (these mappings would be populated the first time `serialize` or `deserialize` is called on a certain class)
However, it may be possible to cache the class's own resolved schema and/or the `dacite` config as new class attributes. 
This way, we don't interfere with the other usages of `avro_schema_to_python` (especially the ones that have a parent).

### PR DESCRIPTION
**Pull request by cmatache-bamfunds**
Fixes #536

### CODE REVIEW

**Comment by marcosschroh** [comment]
Thanks @cmatache-bamfunds 

Could you share the improvements when comparing this PR against the current version? For example, how fast the `serdes` methods will be improved with the PR in %.  Also, a comparison with `fastavro` would be great as well.

**Comment by cmatache-bamfunds** [comment]
Taking this example:
```python
from dataclasses import dataclass
from enum import Enum

from dataclasses_avroschema import AvroModel


class En(Enum):
    a = 'a'
    b = 'b'


@dataclass
class Sch1(AvroModel):
    a: int
    b: float
    c: str
    d: list[str]
    e: En


@dataclass
class Sch2(AvroModel):
    x: dict[str, Sch1]


obj = Sch2(
    x={
        'SBGyKxjfdireQoNwlTnI': Sch1(
            a=2454, b=33083.8861890485, c='swZdoEtJjXUFjnqstXco', d=['lLGQNjeQRxpVGZuLpjZP'], e=En.a,
        ),
        'KgpkxONyPwzqwmZFzcpP': Sch1(
            a=4868, b=-783982970655.952, c='eAscpogeWcubcBndqSAs', d=['tIrpMFcKTfnKwZutHUBj'], e=En.b,
        )
    }
)
ser = obj.serialize()
assert Sch2.deserialize(ser) == obj
```

Performance **before**:
```python
%timeit obj.serialize()  # 1.08 ms ± 52.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
%timeit Sch2.deserialize(ser)  # 545 µs ± 15.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

Performance **after**:
```python
%timeit obj.serialize()  # 90.1 µs ± 2.38 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
%timeit Sch2.deserialize(ser)  # 64.2 µs ± 2.43 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

That is, a ~12X speed up for serialization, and ~8X for deserialization.

I am exposing the `deserialize_to_python` class method such that serdes can be sped up even further by going to 
`pydantic` v2  instead of `dacite` and `asdict + standardize_custom_type` for object reconstruction and `dict` dumps 
respectively. `pydantic` v2 is written in Rust and will be much faster in doing these two computations. 
For example, one can do:

```python
from enum import Enum
from typing import Callable, Any, TypeVar, Type, cast

import pydantic
from pydantic.dataclasses import dataclass as pydantic_dataclass
from dataclasses_avroschema import AvroModel, JsonDict


@pydantic_dataclass(config=pydantic.ConfigDict(use_enum_values=True))
class AvroModelPydanticDataclass(AvroModel):
    # For serialization
    def asdict(self, standardize_factory: Callable[..., Any] | None = None) -> JsonDict:
        return pydantic.RootModel[type(self)].model_dump(self)  # type: ignore[misc,no-any-return]


# For deserialization
AvroT = TypeVar('AvroT', bound=AvroModelPydanticDataclass)


def deserialize_avro(cls: Type[AvroT], serialized: bytes, writer_schema: Type[AvroModel] | None = None) -> AvroT:
    return cast(AvroT, cls(**cls.deserialize_to_python(serialized, writer_schema=writer_schema)))


class En(Enum):
    a = 'a'
    b = 'b'


@pydantic_dataclass
class Sch1(AvroModelPydanticDataclass):
    a: int
    b: float
    c: str
    d: list[str]
    e: En


@pydantic_dataclass
class Sch2(AvroModelPydanticDataclass):
    x: dict[str, Sch1]


obj = Sch2(
    x={
        'SBGyKxjfdireQoNwlTnI': Sch1(
            a=2454, b=33083.8861890485, c='swZdoEtJjXUFjnqstXco', d=['lLGQNjeQRxpVGZuLpjZP'], e=En.a,
        ),
        'KgpkxONyPwzqwmZFzcpP': Sch1(
            a=4868, b=-783982970655.952, c='eAscpogeWcubcBndqSAs', d=['tIrpMFcKTfnKwZutHUBj'], e=En.b,
        )
    }
)
ser = obj.serialize()
assert deserialize_avro(Sch2, ser) == obj

%timeit obj.serialize()  # 58.6 µs ± 1.38 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
%timeit deserialize_avro(Sch2, ser)  # 23.7 µs ± 1.86 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

This opens up the possibility for the users to achieve an ~18X improvement in serialization and ~23X in deserialization.
Other datatypes should still function properly (e.g., `datetime`).

**Comment by marcosschroh** [comment]
Thanks @cmatache-bamfunds  Could you fix the code? The tests are failing

**Comment by cristianmatache** [comment]
> Thanks @cmatache-bamfunds Could you fix the code? The tests are failing

Hi @marcosschroh , this PR is not introducing any new test failures. This PR had a few false positives in `mypy` which caused the build to fail. The tests failing in my PR were already failing in `master`. See https://github.com/marcosschroh/dataclasses-avroschema/actions/runs/10007154620/job/27661267481 
image

The reason the build is not failing is because the exit code of `./scripts/test` only depends on the exit code of `mypy` https://github.com/marcosschroh/dataclasses-avroschema/blob/38ceb46a7d4343dc03cca58f8e121ca9d7f251c5/scripts/test#L10-L12. That is, it doesn't matter if the tests are failing or not, as long as `mypy` passes the build (as a whole) will pass.

**Comment by marcosschroh** [comment]
No @cristianmatache , it does not work on that way. If the `tests`, `linting` or `mypy` fails then the script  finishes with a code different than 0, then the script fails. Just try to do a dummy example with `assert False` in any test and you will see that the `linting` and `mypy` do not run. 

Then, what you see in the image `4 xfailed` has a purpose. The "failing" tests are the one [marked as failing](https://github.com/marcosschroh/dataclasses-avroschema/blob/master/tests/schemas/test_roundtrip.py#L10) which I already know before hand that they are failing.

**Comment by marcosschroh** [comment]
Just check the action https://github.com/marcosschroh/dataclasses-avroschema/actions/runs/10009999830/job/27670163667#step:5:164. You see that it failed because of `dataclasses_avroschema/utils.py:82: error: Argument 1 to "__call__" of "_lru_cache_wrapper" has incompatible type "type[Any]"; expected "Hashable"  [arg-type]
Found 1 error in 1 file (checked 40 source files)` (A change introduced in the PR)

**Comment by cristianmatache** [comment]
You're right, I missed this https://github.com/marcosschroh/dataclasses-avroschema/blob/38ceb46a7d4343dc03cca58f8e121ca9d7f251c5/scripts/test#L1

I know what `xfail` means, but by test failures, I thought you meant the `pytest` failures, because the only issues introduced in the PR were `mypy` failures. Those are more like lint/static checks than actual tests, hence my confusion. Anyway, I added `type: ignore` for the mypy failures.

**Review by marcosschroh — APPROVED** [review]

**Pull request merged**
